name = "todo-list-hono-api-ipss"
main = "src/index.ts"
compatibility_date = "2025-11-24"

[[d1_databases]]
binding = "DB"
database_name = "basic-hono-todos-db"
database_id = "71de3818-7fb4-4eeb-ac65-036fb2c70e40"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "todo-images"

[env.production]
name = "todo-list-hono-api-ipss"

[[env.production.d1_databases]]
binding = "DB"
database_name = "basic-hono-todos-db"
database_id = "71de3818-7fb4-4eeb-ac65-036fb2c70e40"
migrations_dir = "migrations"

[[env.production.r2_buckets]]
binding = "IMAGES"
bucket_name = "todo-images"
